services:
  backend:
    build: .
    ports:
      - "3000:3000" # Exponiendo el puerto 3000
    environment:
      - MONGODB_URI=mongodb+srv://albertoalegrebarazorda:0IkUzYxrHDYpQv9K@cluster0.xhlja.mongodb.net/pacientes?retryWrites=true&w=majority&appName=Cluster0
      - PORT=3000
      - JWT_SECRET=secret
